In [1]:
import cPickle
import sklearn.preprocessing as PPC
import sklearn.cross_validation as CV
from sklearn.svm import SVC
import numpy as np
from pylab import *
#from ubc_AI.data import cross_validation
from pylab import *

In [2]:
clf = SVC( probability=True)
pos = cPickle.load(open('positive.pkl', 'rb'))
neg = cPickle.load(open('negtive.pkl', 'rb'))

In [3]:
posdata = PPC.scale([pos[k] for k in pos], axis=1)
postarget = np.ones(posdata.shape[0])
negdata = PPC.scale([neg[k] for k in neg], axis=1)
negtarget = np.zeros(negdata.shape[0])

In [4]:
data = np.vstack((posdata,negdata))
target = np.hstack((postarget, negtarget))

In [5]:
index = range(len(data))
np.random.shuffle(index)
data = data[index]
target = target[index]

In [6]:
datasize = len(data)


In [7]:
clf.fit(data, target)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
cPickle.dump(clf, open('clfsvmb.pkl', 'wb'), protocol=2)


In [9]:
print(data[1])

[ 1.92494265  0.82873635  0.4268629   1.64177936  0.76830076  1.72125821
  0.72936745  0.83016679  0.99723222  0.41040879  0.83079681  1.40100294
  0.92640917 -0.20110327  1.14548628  0.29303307 -0.41367947 -0.19114431
  0.51814403  0.04934471 -0.2645383   0.25679491 -0.33436384  0.18229086
 -0.09370356  0.10343144 -0.96739902 -0.31929529  0.23316965 -0.27387621
  0.18106863 -0.35526413 -0.71997915  0.00921393 -0.36717721 -0.7020732
 -0.28067489 -0.84837472 -0.92611192 -0.90140339 -0.15219335 -0.27022025
 -0.80460376 -0.61485463 -0.75918283 -1.2621585  -0.7172899  -0.81255179
 -1.37993202 -2.26670519 -2.6070202  -1.76601415 -1.72363414 -2.24138761
 -1.21455347 -2.16475142 -0.50001124 -1.46150858 -1.26013148 -1.3133286
 -1.99349725 -0.93068397 -1.47957898 -1.08809486  0.37576712 -0.62451276
 -0.91071219 -0.07069505  0.27336919  0.3763276  -0.21978298  0.11495703
  0.18817635  0.4232841   0.8821862  -0.11146465  0.22549644  1.17506492
  0.47923241  0.73891141  0.20209276  1.76984309  0.5

In [10]:
clf.predict(data[1])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.])

In [11]:
clf.predict(data[100])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.])

In [12]:
clf.predict(data[101])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [13]:
clf.predict(data[200])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.])

In [14]:
from sklearn.neighbors.nearest_centroid import NearestCentroid

In [15]:
clfknn = NearestCentroid()

In [16]:
clfknn.fit(data, target)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [17]:
clfknn.predict(data[101])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [18]:
clfknn.predict(data[100])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.])

In [19]:
clfknn.predict(data[1])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.])

In [20]:
clfknn.predict(data[199])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
clfgnb = GaussianNB()

In [23]:
clfgnb.fit(data, target)

GaussianNB()

In [24]:
clfgnb.predict(data[199])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [25]:
from sklearn import tree

In [26]:
clftree = tree.DecisionTreeClassifier()

In [27]:
clftree.fit(data, target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [28]:
clftree.predict(data[199])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
clfrandtree=RandomForestClassifier(n_estimators=10)

In [31]:
clfrandtree.fit(data,target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
clfrandtree.predict(data[199])

C:\Users\Rui\Anaconda3\envs\python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 1.])